### ISSUE TITLE
Pop down notifications are not styled correctly.

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#22]
If you start `gtk3-widget-factory` and goto Page 2 set the spinner in the top left of the page to 45. This will make a popdown appear. The popdown and the button within it are not styled correctly. This issue affects Ambiant-MATE, Ambiant-MATE-Dark and Radiant-MATE.

## Ambiant-MATE

The popdown color is correct in Ambiant-MATE but the buttons are not styled correctly. Can the border around the text and buttons be removed, as you have done in BlackMATE.

![popdown-ambiant-mate](https://user-images.githubusercontent.com/304639/36928227-fd33aa78-1e7b-11e8-83be-fc6642c9c6d7.png)

## Ambiant-MATE-Dark

The popdown color is not correct (too dark) in Ambiant-MATE-Dark and the buttons are not styled correctly. Can the border around the text and buttons be removed, as you have done in BlackMATE.

![popdown-ambiant-mate-dark](https://user-images.githubusercontent.com/304639/36928231-039fd7a6-1e7c-11e8-8843-0d502ede6f8e.png)

## Radiant-MATE

The popdown color is not correct (too dark) in Radiant-MATE and the buttons are not styled correctly. Can the border around the text and buttons be removed, as you have done in BlackMATE.

![popdown-radiant-mate](https://user-images.githubusercontent.com/304639/36928232-0796cc5c-1e7c-11e8-9e4e-848dda674684.png)

This was tested on Ubuntu MATE 18.04 (daily) with git master of `ubuntu-mate-artwork`. @raveit65 Please can you take a look at this?

**Comment by Dolsilwa** [comment]
In Ambiant-MATE, in gtk-widgets.css, changing background-image (in .app-notification button, line 754) to "none" fixes problem with dark background on buttons in popdown (app-notification widget).  You should also change border-color to "transparent" to get rid of blue border around buttons. And change box-shadow to "none" to get rid of lightborder.
after change it should look like this:

.app-notification button,
.app-notification headerbar button.titlebutton,
headerbar .app-notification button.titlebutton,
.app-notification .titlebar button.titlebutton,
.titlebar .app-notification button.titlebutton,
.app-notification calendar.header button.titlebutton,
calendar.header .app-notification button.titlebutton,
.app-notification.frame button {
    color: @theme_dark_fg_color;
    border-color: transparent;
    background-image: none;
    background-clip: padding-box;
    box-shadow: none;
    text-shadow: none;
    -gtk-icon-shadow: 0 1px black;
    outline-color: rgba(238, 238, 236, 0.3);
    border-radius: 3px;
    padding: 0 0px 2px 0px;
}

border-color in .app-notification button:hover (now line 790) also should be changed to get rid ugly border around hovered button.

and white border around text and buttons has something to do with .frame and frame > border (now line 877 and 878) because changing border-color there to "transparet" solves this problem but may cause problems elsewhere.

After all those changes it looks like this:
![1](https://user-images.githubusercontent.com/36594353/36936828-6fa3db62-1f0a-11e8-8261-0e003a9cf2b1.png)

**Comment by raveit65** [comment]
Please do not test, this is to bad :)
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/23/commits/8b8cd02be0af5e4b30f9f0c6971140ab404c09aa

**Comment by flexiondotorg** [comment]
@raveit65 Looks great, thanks! Please go ahead and give Ambiant-MATE-Dark and and Radiant-MATE similar treatment :smile:

**Comment by flexiondotorg** [comment]
Close by #23
